# Generated by Django 4.2.13 on 2024-05-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remoteauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
