# Generated by Django 4.2.13 on 2024-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('game_played_date', models.DateField(verbose_name='date played')),
            ],
        ),
    ]
