# Generated by Django 4.2.13 on 2024-06-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='profile_img_url',
            field=models.URLField(blank=True),
        ),
    ]
