# Generated by Django 4.2.13 on 2024-05-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_players_mfa_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='forty_two_student',
        ),
        migrations.AddField(
            model_name='players',
            name='friends',
            field=models.ManyToManyField(blank=True, to='players.players'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='players.players')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='players.players')),
            ],
        ),
    ]
